--- # ------------------------------------------------------------------------------
name: macOS

# TODO: Possibly add on-push-paths triggers below to only trigger self-tests when .c, .h, .cc,
# .cmake, .py, .sh, CMakeLists.txt and workflow files are pushed
on: push

# Environment variables that can be read during jobs
env:
  CTEST_OUTPUT_ON_FAILURE: 1
  # Enable oversubscription for OpenMPI to handle MPI-enabled tests requiring
  # more processors than are available
  OMPI_MCA_rmaps_base_oversubscribe: 1

# ------------------------------------------------------------------------------

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        mpi: ["OFF", "ON"]

    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install cmake ninja openblas && brew reinstall gcc

      - name: Install MPI dependencies (if required)
        if: matrix.mpi == 'ON'
        run: brew install open-mpi

      - name: Configure
        run: cmake -G Ninja -DOOMPH_USE_OPENBLAS_FROM=$(brew --prefix openblas) -DOOMPH_ENABLE_MPI=${{ matrix.mpi }} -B build

      - name: Build/install
        id: build
        run: cmake --build build

      - name: Upload build logs
        uses: actions/upload-artifact@v3
        with:
          name: build_logs-os_${{ runner.os }}-mpi_${{ matrix.mpi }}.log
          path: ./build/logs/

      - name: Propagate build status
        if: steps.build.outcome == 'failure'
        run: exit 1
